server:
  port: 8080

spring:
  application:
    name: chat-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        file-extension: yml
    gateway:
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
